pipeline:
  build:
    image: node:8.9-alpine
    commands:
      - npm install
      - npm test

  publish:
    image: plugins/docker
    repo: aafrey/drone-test
    tags: [ 0.0.1, latest ]
    secrets: [ docker_username, docker_password ]

