pipeline:
  build:
    image: node:8.9-alpine
    commands:
      - npm install
      - npm run build
      - npm test

  publish:
    image: plugins/docker
    repo: aafrey/drone-test
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
    secrets: [ docker_username, docker_password ]

  rancher:
    image: peloton/drone-rancher
    url: http://admin.zi.gy
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: drone-hello/hello
    docker_image: aafrey/drone-test:0.0.1
    secrets: [ rancher_access_key, rancher_secret_key ]
