pipeline:
  build:
    image: node:8.9-alpine
    commands:
      - npm install
      - npm test

  publish:
    image: plugins/docker
    repo: aafrey/drone-test
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    tags: [ 0.0.1, latest ]
